# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RACStudy' do
  pod 'ReactiveCocoa', '~> 2.5'        # RAC
  pod 'MJRefresh', '~> 3.1.12'         # 刷新
  pod 'AFNetworking', '~> 2.5.4'       # 网络请求
  pod 'MJExtension', '~> 2.0.4'        # 字典转模型
  pod 'SDWebImage','~> 3.7.5'         # 图片处理
end
